# Generated by Django 5.1.1 on 2024-10-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0003_alter_producto_precio_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
