# Generated by Django 5.1.1 on 2024-11-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0004_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=100),
        ),
    ]
